version: "3.9"

services:
  web:
    build: .
    env_file: .env
    command: gunicorn --bind 0.0.0.0:5000 "app:create_app('production')"
    expose:
      - "5000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/app/static:ro
    depends_on:
      - web
